import { spawnSync } from "child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";

import { BufferSource, Input, MP4 } from "mediabunny";

import { MP4Callback, type Track } from "../src/extra";
import type { Mp4Output } from "../src/extra/processor/mp4";
import type { Transport } from "../src/transport";

export function load(name: string) {
  const base = __dirname;
  const data = readFileSync(`${base}/data/` + name);
  return data;
}

export function createMockTransportPair(): [Transport, Transport] {
  class Mock implements Transport {
    onData!: (buf: Buffer) => void;
    target!: Mock;

    send(buf: Buffer) {
      this.target.onData(buf);
    }
    close() {}
  }

  const a = new Mock();
  const b = new Mock();
  a.target = b;
  b.target = a;

  return [a, b];
}

export async function collectMp4Buffer(
  tracks: Track[],
  act: (mp4: MP4Callback) => void | Promise<void>,
) {
  const outputs = await collectMp4Outputs(tracks, act);
  return mp4OutputsToBuffer(outputs);
}

export function mp4OutputsToBuffer(outputs: Mp4Output[]) {
  const chunks = outputs
    .filter((output): output is Extract<Mp4Output, { data: Uint8Array }> => {
      return "data" in output;
    })
    .map((output) => output.data);

  return Buffer.concat(chunks.map((chunk) => Buffer.from(chunk)));
}

export async function collectMp4Outputs(
  tracks: Track[],
  act: (mp4: MP4Callback) => void | Promise<void>,
  options: {
    callbackDelay?: number;
  } = {},
) {
  const outputs: Mp4Output[] = [];
  const mp4 = new MP4Callback(tracks);

  let resolveDone!: () => void;
  let rejectDone!: (error: Error) => void;
  const done = new Promise<void>((resolve, reject) => {
    resolveDone = resolve;
    rejectDone = reject;
  });

  mp4.pipe(async (output) => {
    if (options.callbackDelay) {
      await sleep(options.callbackDelay);
    }
    outputs.push(output);
    if ("eol" in output && output.eol) {
      resolveDone();
    }
  });

  try {
    await act(mp4);
    await withTimeout(done, 5_000);
  } catch (error) {
    rejectDone(error as Error);
    throw error;
  }

  return outputs;
}

export type Mp4TestFrame = {
  data: Buffer;
  isKeyframe: boolean;
  time: number;
};

export function createFrame(
  data: Buffer,
  isKeyframe: boolean,
  time: number,
): Mp4TestFrame {
  return { data, isKeyframe, time };
}

export function createAudioFrames() {
  return [
    createFrame(Buffer.from([0xf8, 0xff, 0xfe, 0x01]), true, 0),
    createFrame(Buffer.from([0xf8, 0xff, 0xfe, 0x02]), true, 20),
    createFrame(Buffer.from([0xf8, 0xff, 0xfe, 0x03]), true, 40),
  ];
}

/** Baseline H.264 SPS (1920x1080, SAR 1:1) */
export const avcTestSps =
  "000000016742001eda01e0089f970110000003000100000300320f183196";
/** PPS paired with {@link avcTestSps} */
export const avcTestPps = "0000000168ce06e2";
/** IDR slice without parameter sets */
export const avcTestIdrSlice = "0000000165888421a0";

/**
 * SPS/PPS + IDR keyframe followed by two delta frames.
 * `timeOffset` shifts every frame time (ms).
 */
export function createVideoFrames(timeOffset = 0) {
  return [
    createFrame(
      Buffer.from(avcTestSps + avcTestPps + avcTestIdrSlice, "hex"),
      true,
      timeOffset,
    ),
    createFrame(Buffer.from("00000001419a2211", "hex"), false, timeOffset + 33),
    createFrame(Buffer.from("00000001419a3344", "hex"), false, timeOffset + 66),
  ];
}

export function createAvcKeyframeWithoutParameterSets(time: number) {
  return createFrame(Buffer.from(avcTestIdrSlice, "hex"), true, time);
}

export function createAvcKeyframeWithTruncatedSps(time: number) {
  return createFrame(
    Buffer.from("000000016742" + avcTestPps + avcTestIdrSlice, "hex"),
    true,
    time,
  );
}

export function createVideoTrack(
  dimensions: Pick<Track, "width" | "height"> = {},
  trackNumber = 1,
): Track {
  return {
    ...dimensions,
    kind: "video",
    codec: "avc1",
    clockRate: 90_000,
    trackNumber,
  };
}

export function createAudioTrack(trackNumber = 1): Track {
  return {
    kind: "audio",
    codec: "opus",
    clockRate: 48_000,
    trackNumber,
  };
}

const h264NaluType = { idr: 5, sps: 7, pps: 8, aud: 9 } as const;

/**
 * Loads an H.264 Annex B fixture generated by `tests/data/h264/generate.sh`
 * and splits it into access units (one frame each) at every AUD NAL.
 */
export function loadH264AccessUnits(name: string, fps = 30): Mp4TestFrame[] {
  const accessUnits: Buffer[][] = [];
  for (const nalu of splitAnnexBNalUnits(load(`h264/${name}`))) {
    if ((nalu[0] & 0x1f) === h264NaluType.aud || accessUnits.length === 0) {
      accessUnits.push([]);
    }
    accessUnits.at(-1)!.push(nalu);
  }

  return accessUnits.map((nalUnits, i) =>
    createFrame(
      joinAnnexBNalUnits(nalUnits),
      nalUnits.some((nalu) => (nalu[0] & 0x1f) === h264NaluType.idr),
      (i * 1000) / fps,
    ),
  );
}

/** Returns a copy of the frame without SPS / PPS NAL units. */
export function stripH264ParameterSets(frame: Mp4TestFrame): Mp4TestFrame {
  const nalUnits = splitAnnexBNalUnits(frame.data).filter((nalu) => {
    const type = nalu[0] & 0x1f;
    return type !== h264NaluType.sps && type !== h264NaluType.pps;
  });
  return { ...frame, data: joinAnnexBNalUnits(nalUnits) };
}

/** Returns a copy of the frame whose SPS NAL unit is cut to `length` bytes. */
export function truncateH264Sps(
  frame: Mp4TestFrame,
  length: number,
): Mp4TestFrame {
  const nalUnits = splitAnnexBNalUnits(frame.data).map((nalu) =>
    (nalu[0] & 0x1f) === h264NaluType.sps ? nalu.subarray(0, length) : nalu,
  );
  return { ...frame, data: joinAnnexBNalUnits(nalUnits) };
}

function splitAnnexBNalUnits(data: Buffer) {
  const starts: { codeStart: number; payloadStart: number }[] = [];
  for (let i = 0; i + 2 < data.length; i++) {
    if (data[i] === 0 && data[i + 1] === 0 && data[i + 2] === 1) {
      const codeStart = i > 0 && data[i - 1] === 0 ? i - 1 : i;
      starts.push({ codeStart, payloadStart: i + 3 });
      i += 2;
    }
  }
  return starts.map(({ payloadStart }, i) =>
    data.subarray(payloadStart, starts[i + 1]?.codeStart ?? data.length),
  );
}

function joinAnnexBNalUnits(nalUnits: Buffer[]) {
  const startCode = Buffer.from([0, 0, 0, 1]);
  return Buffer.concat(nalUnits.flatMap((nalu) => [startCode, nalu]));
}

/**
 * Feeds the frames to an MP4Callback (video, then optional audio frames
 * interleaved by index), sends EOL on every track and collects the outputs.
 */
export function muxMp4Frames(
  tracks: Track[],
  videoFrames: Mp4TestFrame[],
  audioFrames: Mp4TestFrame[] = [],
) {
  return collectMp4Outputs(tracks, (mp4) => {
    for (let i = 0; i < Math.max(videoFrames.length, audioFrames.length); i++) {
      if (videoFrames[i]) {
        mp4.inputVideo({ frame: videoFrames[i] });
      }
      if (audioFrames[i]) {
        mp4.inputAudio({ frame: audioFrames[i] });
      }
    }
    if (audioFrames.length > 0) {
      mp4.inputAudio({ eol: true });
    }
    mp4.inputVideo({ eol: true });
  });
}

export type FfprobeVideoResult = {
  profile: string;
  width: number;
  height: number;
  sampleAspectRatio: string;
  displayAspectRatio: string;
  decodedFrames: number;
  /** stderr of ffprobe at `-v error`; empty when decoding had no errors */
  errors: string;
};

export function isFfprobeAvailable() {
  return spawnSync("ffprobe", ["-version"]).status === 0;
}

/**
 * Decodes every frame of the first video stream with ffprobe
 * and returns the stream parameters seen by FFmpeg.
 */
export function probeMp4Video(buffer: Buffer): FfprobeVideoResult {
  const dir = mkdtempSync(join(tmpdir(), "werift-rtp-mp4-"));
  try {
    const path = join(dir, "output.mp4");
    writeFileSync(path, buffer);
    const result = spawnSync(
      "ffprobe",
      [
        "-v",
        "error",
        "-count_frames",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=profile,width,height,sample_aspect_ratio,display_aspect_ratio,nb_read_frames",
        "-of",
        "json",
        path,
      ],
      { encoding: "utf8" },
    );
    if (result.status !== 0) {
      throw new Error(`ffprobe failed: ${result.stderr}`);
    }
    const [stream] = JSON.parse(result.stdout).streams;
    return {
      profile: stream.profile,
      width: stream.width,
      height: stream.height,
      sampleAspectRatio: stream.sample_aspect_ratio,
      displayAspectRatio: stream.display_aspect_ratio,
      decodedFrames: Number(stream.nb_read_frames),
      errors: result.stderr,
    };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

export function createMp4Input(buffer: Buffer) {
  return new Input({
    source: new BufferSource(buffer),
    formats: [MP4],
  });
}

async function withTimeout<T>(promise: Promise<T>, timeout: number) {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([
      promise,
      new Promise<T>((_, reject) => {
        timer = setTimeout(() => {
          reject(new Error(`timed out after ${timeout}ms`));
        }, timeout);
      }),
    ]);
  } finally {
    if (timer) {
      clearTimeout(timer);
    }
  }
}

function sleep(timeout: number) {
  return new Promise<void>((resolve) => {
    setTimeout(resolve, timeout);
  });
}
