export type ExampleKind =
  | "datachannel"
  | "media-inbound"
  | "media-record"
  | "close-dc"
  | "close-pc"
  | "ice-restart"
  | "process-exit"
  | "node-gst";

export type ClientKind = "babel" | "vite" | "none";

export type BinaryNeed = "gst" | "ffmpeg";

export type CatalogEntry = {
  id: string;
  /** Catalog group for tests and AGENTS.md */
  group: "browser" | "ffmpeg-gstreamer";
  node: string[];
  html?: string;
  port: number;
  client: ClientKind;
  kind: ExampleKind;
  binary?: BinaryNeed;
  /** gst/ffmpeg を spawn するポート。binary がなくても生存 Assert 対象になる */
  extraGstPorts?: number[];
  click?: string;
  fileInput?: "webm" | "mp4";
  skipIfNoAv1?: boolean;
  /** Where media is asserted. recvonly/codec demos send browser→werift. */
  inbound?: "browser" | "werift";
  /** Server log markers for each werift-side inbound simulcast track. */
  weriftRtpLogs?: string[];
  /** UDP port the example forwards RTP to; harness binds and counts packets */
  rtpForwardPort?: number;
  env?: Record<string, string>;
  waitLog?: string | RegExp | false;
  expectExit?: number;
  outputGlob?: string;
  /** Seconds to wait after connect before asserting a recording file */
  recordWaitMs?: number;
  /** Validate the resulting container with ffprobe. */
  outputContainer?: "webm" | "mp4";
  /** Stop a long-running example after its output has been observed. */
  stopAfterOutput?: boolean;
  /** Log marker proving RTP reached the recording pipeline. */
  rtpLog?: string | RegExp;
};

export type ExcludedExample = {
  path: string;
  reason: string;
};

/**
 * Examples that this harness actually launches.
 * Keep in sync with examples/AGENTS.md.
 */
export const catalog: CatalogEntry[] = [
  {
    id: "datachannel-offer",
    group: "browser",
    node: ["datachannel/offer.ts"],
    html: "datachannel/answer.html",
    port: 8888,
    client: "babel",
    kind: "datachannel",
  },
  {
    id: "datachannel-answer",
    group: "browser",
    node: ["datachannel/answer.ts"],
    html: "datachannel/offer.html",
    port: 8888,
    client: "babel",
    kind: "datachannel",
  },
  {
    id: "datachannel-string",
    group: "browser",
    node: ["datachannel/string.ts"],
    html: "datachannel/string.html",
    port: 8888,
    client: "babel",
    kind: "datachannel",
  },
  {
    // closed.ts is the answer; closing.html is the offer that closes the DC.
    id: "close-dc-closed",
    group: "browser",
    node: ["close/dc/closed.ts"],
    html: "close/dc/closing.html",
    port: 8888,
    client: "babel",
    kind: "close-dc",
  },
  {
    // closing.ts is the offer that closes; closed.html is the answer.
    id: "close-dc-closing",
    group: "browser",
    node: ["close/dc/closing.ts"],
    html: "close/dc/closed.html",
    port: 8888,
    client: "babel",
    kind: "close-dc",
  },
  {
    id: "close-pc-closed",
    group: "browser",
    node: ["close/pc/closed.ts"],
    html: "close/pc/closing.html",
    port: 8888,
    client: "babel",
    kind: "close-pc",
  },
  {
    id: "close-pc-closing",
    group: "browser",
    node: ["close/pc/closing.ts"],
    html: "close/pc/closed.html",
    port: 8888,
    client: "babel",
    kind: "close-pc",
  },
  {
    id: "certificate-offer",
    group: "browser",
    node: ["certificate/offer.ts"],
    html: "certificate/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "ice-restart",
    group: "browser",
    node: ["ice/restart/offer.ts"],
    html: "ice/restart/answer.html",
    port: 8888,
    client: "babel",
    kind: "ice-restart",
  },
  {
    id: "ice-trickle-offer",
    group: "browser",
    node: ["ice/trickle/offer.ts"],
    html: "ice/trickle/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "ice-trickle-dc",
    group: "browser",
    node: ["ice/trickle/dc.ts"],
    html: "ice/trickle/dc.html",
    port: 12223,
    client: "babel",
    kind: "datachannel",
  },
  {
    id: "sendrecv-offer",
    group: "browser",
    node: ["mediachannel/sendrecv/offer.ts"],
    html: "mediachannel/sendrecv/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "sendrecv-answer",
    group: "browser",
    node: ["mediachannel/sendrecv/answer.ts"],
    html: "mediachannel/sendrecv/offer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "sendrecv-multi",
    group: "browser",
    node: ["mediachannel/sendrecv/multi_offer.ts"],
    html: "mediachannel/sendrecv/multi_answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "recvonly-offer",
    group: "browser",
    node: ["mediachannel/recvonly/offer.ts"],
    html: "mediachannel/recvonly/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    inbound: "werift",
    rtpForwardPort: 4002,
  },
  {
    id: "recvonly-multi",
    group: "browser",
    node: ["mediachannel/recvonly/multi_offer.ts"],
    html: "mediachannel/recvonly/multi_answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    inbound: "werift",
    rtpForwardPort: 4002,
  },
  {
    id: "recvonly-dump",
    group: "browser",
    node: ["mediachannel/recvonly/dump.ts"],
    html: "mediachannel/recvonly/answer.html",
    port: 8888,
    client: "babel",
    kind: "process-exit",
    expectExit: 0,
  },
  {
    id: "rtp-forward",
    group: "browser",
    node: ["mediachannel/rtp_forward/offer.ts"],
    html: "mediachannel/rtp_forward/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    inbound: "werift",
    rtpForwardPort: 1234,
  },
  {
    id: "pubsub",
    group: "browser",
    node: ["mediachannel/pubsub/offer.ts"],
    html: "mediachannel/pubsub/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    click: "publish",
  },
  {
    id: "sdp-offer",
    group: "browser",
    node: ["mediachannel/sdp/offer.ts"],
    html: "mediachannel/sdp/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "sdp-offer-offer",
    group: "browser",
    node: ["mediachannel/sdp/offer_offer.ts"],
    html: "mediachannel/sdp/answer_answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "rtx-offer",
    group: "browser",
    node: ["mediachannel/rtx/offer.ts"],
    html: "mediachannel/rtx/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "rtx-simulcast",
    group: "browser",
    node: ["mediachannel/rtx/simulcast_offer.ts"],
    html: "mediachannel/rtx/simulcast_answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "simulcast-offer",
    group: "browser",
    node: ["mediachannel/simulcast/offer.ts"],
    html: "mediachannel/simulcast/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "simulcast-answer",
    group: "browser",
    node: ["mediachannel/simulcast/answer.ts"],
    html: "mediachannel/simulcast/offer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "simulcast-select",
    group: "browser",
    node: ["mediachannel/simulcast/select.ts"],
    html: "mediachannel/simulcast/select.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "simulcast-multiple",
    group: "browser",
    node: ["mediachannel/simulcast/multiple.ts"],
    html: "mediachannel/simulcast/multiple.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    inbound: "werift",
    weriftRtpLogs: ["trackA.onReceiveRtp", "trackB.onReceiveRtp"],
  },
  {
    id: "simulcast-multiple-answer",
    group: "browser",
    node: ["mediachannel/simulcast/multiple_answer.ts"],
    html: "mediachannel/simulcast/multiple_answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    inbound: "werift",
    weriftRtpLogs: ["track.onReceiveRtp A", "track.onReceiveRtp B"],
  },
  {
    id: "simulcast-abr",
    group: "browser",
    node: ["mediachannel/simulcast/abr.ts"],
    html: "mediachannel/simulcast/abr.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "simulcast-twcc",
    group: "browser",
    node: ["mediachannel/simulcast/twcc.ts"],
    html: "mediachannel/simulcast/twcc.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "twcc-offer",
    group: "browser",
    node: ["mediachannel/twcc/offer.ts"],
    html: "mediachannel/twcc/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "twcc-multitrack",
    group: "browser",
    node: ["mediachannel/twcc/multitrack.ts"],
    html: "mediachannel/twcc/multitrack.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
  },
  {
    id: "red-sendrecv",
    group: "browser",
    node: ["mediachannel/red/sendrecv.ts"],
    html: "mediachannel/red/sendrecv.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    fileInput: "webm",
  },
  {
    id: "red-recv",
    group: "browser",
    node: ["mediachannel/red/recv.ts"],
    html: "mediachannel/red/recv.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    inbound: "werift",
    rtpForwardPort: 4005,
  },
  {
    id: "codec-vp8",
    group: "browser",
    node: ["mediachannel/codec/vp8.ts"],
    html: "mediachannel/codec/index.html",
    port: 8888,
    client: "vite",
    kind: "media-inbound",
    inbound: "werift",
  },
  {
    id: "codec-vp9",
    group: "browser",
    node: ["mediachannel/codec/vp9.ts"],
    html: "mediachannel/codec/index.html",
    port: 8888,
    client: "vite",
    kind: "media-inbound",
    inbound: "werift",
  },
  {
    id: "codec-h264",
    group: "browser",
    node: ["mediachannel/codec/h264.ts"],
    html: "mediachannel/codec/index.html",
    port: 8888,
    client: "vite",
    kind: "media-inbound",
    inbound: "werift",
  },
  {
    id: "codec-av1",
    group: "browser",
    node: ["mediachannel/codec/av1.ts"],
    html: "mediachannel/codec/index.html",
    port: 8888,
    client: "vite",
    kind: "media-inbound",
    inbound: "werift",
    skipIfNoAv1: true,
  },
  {
    id: "save-vp8",
    group: "browser",
    node: ["save_to_disk/vp8.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "*.webm",
    recordWaitMs: 6_000,
  },
  {
    id: "save-vp9",
    group: "browser",
    node: ["save_to_disk/vp9.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "*.webm",
    recordWaitMs: 6_000,
  },
  {
    id: "save-h264",
    group: "browser",
    node: ["save_to_disk/h264.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "*.webm",
    recordWaitMs: 20_000,
  },
  {
    id: "save-opus",
    group: "browser",
    node: ["save_to_disk/opus.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "*.webm",
    recordWaitMs: 6_000,
  },
  {
    id: "save-av1x",
    group: "browser",
    node: ["save_to_disk/av1x.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "*.webm",
    recordWaitMs: 6_000,
    skipIfNoAv1: true,
  },
  {
    id: "save-pipeline",
    group: "browser",
    node: ["save_to_disk/pipeline.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "output-*.webm",
    recordWaitMs: 11_000,
  },
  {
    id: "save-mp4-h264",
    group: "browser",
    node: ["save_to_disk/mp4/h264.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "output-*.mp4",
    recordWaitMs: 11_000,
  },
  {
    id: "save-mp4-opus",
    group: "browser",
    node: ["save_to_disk/mp4/opus.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "output-*.mp4",
    recordWaitMs: 11_000,
  },
  {
    id: "save-mp4-av",
    group: "browser",
    node: ["save_to_disk/mp4/av.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-record",
    outputGlob: "output-*.mp4",
    recordWaitMs: 60_000,
  },
  {
    id: "save-dtx",
    group: "browser",
    node: ["save_to_disk/dtx/server.ts"],
    html: "save_to_disk/dtx/index.html",
    port: 8878,
    client: "vite",
    kind: "media-record",
    fileInput: "webm",
    outputGlob: "output-*.webm",
    recordWaitMs: 11_000,
  },
  {
    id: "save-encoded-transform",
    group: "browser",
    node: ["save_to_disk/encodedTransform/server.ts"],
    html: "save_to_disk/encodedTransform/index.html",
    port: 8888,
    client: "vite",
    kind: "media-record",
    outputGlob: "encoded.webm",
    recordWaitMs: 16_000,
  },
  {
    id: "interop-browser",
    group: "browser",
    node: ["interop/server.ts"],
    html: "interop/index.html",
    port: 8080,
    client: "babel",
    kind: "media-inbound",
    click: "Start",
  },
  {
    id: "sendonly-gst",
    group: "ffmpeg-gstreamer",
    node: ["mediachannel/sendonly/offer.ts"],
    html: "mediachannel/sendonly/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    binary: "gst",
  },
  {
    id: "sendonly-ffmpeg",
    group: "ffmpeg-gstreamer",
    node: ["mediachannel/sendonly/ffmpeg.ts"],
    html: "mediachannel/sendonly/answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    binary: "ffmpeg",
  },
  {
    id: "sendonly-multi",
    group: "ffmpeg-gstreamer",
    node: ["mediachannel/sendonly/multi_offer.ts"],
    html: "mediachannel/sendonly/multi_answer.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    binary: "gst",
    extraGstPorts: [5000, 5001],
  },
  {
    // フィクスチャ webm 再生。gst/ffmpeg 子プロセスは無いので binary は付けない（生存 Assert 対象外）。
    id: "sendonly-av",
    group: "ffmpeg-gstreamer",
    node: ["mediachannel/sendonly/av.ts"],
    html: "mediachannel/sendonly/av.html",
    port: 8881,
    client: "babel",
    kind: "media-inbound",
    click: "start",
  },
  {
    id: "red-send-gst",
    group: "ffmpeg-gstreamer",
    node: ["mediachannel/red/send.ts"],
    html: "mediachannel/red/send.html",
    port: 8888,
    client: "babel",
    kind: "media-inbound",
    binary: "gst",
  },
  {
    id: "red-record-gst",
    group: "ffmpeg-gstreamer",
    node: ["mediachannel/red/record/gst.ts"],
    html: "mediachannel/red/record/index.html",
    port: 8888,
    client: "vite",
    kind: "process-exit",
    binary: "gst",
    fileInput: "webm",
    expectExit: 0,
    outputGlob: "opus.webm",
    recordWaitMs: 7_000,
    outputContainer: "webm",
    rtpLog: /received RTP packets=[1-9]\d*/,
  },
  {
    id: "save-gstreamer",
    group: "ffmpeg-gstreamer",
    node: ["save_to_disk/gstreamer.ts"],
    html: "save_to_disk/answer.html",
    port: 8878,
    client: "babel",
    kind: "media-inbound",
    binary: "gst",
    outputGlob: "capture.webm",
    outputContainer: "webm",
    stopAfterOutput: true,
  },
  {
    id: "save-gst-recoder",
    group: "ffmpeg-gstreamer",
    node: ["save_to_disk/gst/recoder.ts"],
    html: "save_to_disk/gst/index.html",
    port: 8888,
    client: "vite",
    kind: "media-inbound",
    binary: "gst",
    inbound: "werift",
    outputGlob: "*.webm",
  },
  {
    id: "save-packetloss-gst",
    group: "ffmpeg-gstreamer",
    node: ["save_to_disk/packetloss/gst.ts"],
    html: "save_to_disk/packetloss/index.html",
    port: 8888,
    client: "vite",
    kind: "media-record",
    binary: "gst",
    fileInput: "webm",
    outputGlob: "gst.webm",
    recordWaitMs: 16_000,
  },
  {
    id: "save-rtp-gst",
    group: "ffmpeg-gstreamer",
    node: ["save_to_disk/rtp.ts"],
    port: 0,
    client: "none",
    kind: "node-gst",
    binary: "gst",
    waitLog: "start",
    outputGlob: "rtp.webm",
    recordWaitMs: 6_000,
  },
  {
    id: "interop-client-gst",
    group: "ffmpeg-gstreamer",
    node: ["interop/server.ts", "interop/client.ts"],
    port: 8080,
    client: "none",
    kind: "node-gst",
    binary: "gst",
    waitLog: "start",
    expectExit: 0,
  },
];

export const excluded: ExcludedExample[] = [
  { path: "untested/", reason: "E2E対象外の既存サンプルを集約" },
  { path: "packages/*/examples", reason: "本チケット範囲外" },
  { path: "examples/turn-loopback", reason: "既存 chrome-e2e でカバー" },
];

export function catalogById(id: string) {
  const entry = catalog.find((item) => item.id === id);
  if (!entry) {
    throw new Error(`unknown catalog id: ${id}`);
  }
  return entry;
}

export function catalogByGroup(group: CatalogEntry["group"]) {
  return catalog.filter((item) => item.group === group);
}
